### ISSUE TITLE
vue-language-server

### ISSUE THREAD

**Issue by drewbeno1** [catgoose/nvim#2]
Did you hit the problem with the vue-language-server and the fileWatcher causing it not to attach? I can't find any good info online ! Thanks !

**Comment by catgoose** [comment]
No, I haven't had that issue, but I also haven't done any vue development in a month or so. I can check tomorrow.

What error are you getting exactly?

**Comment by drewbeno1** [comment]
Looks like its an incompatibility problem. Check out this [thread](https://github.com/vuejs/language-tools/issues/4707#issuecomment-2303569142). 

When you open up a vue file, the Volar LSP won't attach and it throws a long error, but here's the gist of it: 
[ERROR][2024-08-22 09:31:24] ... 
fileWatcher = server.watchFiles(['**/*.{' + [...watchingExtensions].join(',') + '}']);
\n^\n\n
TypeError: server.watchFiles is not a function\n    at updateFileWatcher 

No worries if you haven't seen it. I just figured i'd ask around to other vue & neovim users. Thanks!

**Comment by catgoose** [comment]
![image](https://github.com/user-attachments/assets/f6a57b6d-5384-415f-b676-108f0b12117f)

I don't seem to have an issue using these versions installed locally to the project:

```json
{
  "@vue/language-server": "^2.0.29",
  "typescript": "~5.5.4"
}
```

I have found the only way to get volar/typescript working the way I want it is to set the `tdsk` in lspconfig: https://github.com/catgoose/nvim/blob/main/lua/plugins/lspconfig.lua#L253-L271

**Comment by drewbeno1** [comment]
Yeah i have tsdk set for me as well. Looks like i have same vls version but an older typescript. I updated it to 5.5.4 and still same problem for me. IDK man, thanks for trying to help!

**Comment by drewbeno1** [comment]
I was able to get it working by updateing my volar dependencies. Thanks for responding man, love your setup!
